version: '3.1'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - odoo-network

  odoo:
    image: odoo:19.0
    container_name: odoo
    depends_on:
      - db
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
    networks:
      - odoo-network
    restart: unless-stopped

volumes:
  odoo-db-data:
  odoo-web-data:

networks:
  odoo-network:
    driver: bridge
